Src/ListingRepository.Web/ListingRepository.Web/ViewModels/Reports/DetailedUpsellSearchViewModel.cs
using System.Collections.Generic;
using Postmedia.ListingRepository.DTO;

namespace Postmedia.ListingRepository.Web.ViewModels.Reports
{
    public class DetailedUpsellSearchViewModel
    {
        public DetailedUpsellCriteriaViewModel DetailedUpsellCriteria { get; set; }
        public List<DetailedUpsellDetailViewModel> DetailedUpsellResults { get; set; }

        // lookups
        public List<Division> Divisions { get; set; }
        public List<SourceSystemLookup> Sources { get; set; }
        public List<Publication> Publications { get; set; }
        public List<UpsellValueLookup> UpsellValues { get; set; }
        public List<ListingStatusLookup> Status { get; set; }
    }
}

Src/ListingRepository.Web/ListingRepository.Web/ViewModels/Reports/Working/QRCodeUrlSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Postmedia.ListingRepository.DTO;
using Postmedia.ListingRepository.DTO.Reports;

namespace Postmedia.ListingRepository.Web.ViewModels.Reports.Working
{
    public class QRCodeUrlSearchViewModel
    {
        public QRCodeUrlCriteriaViewModel QrCodeUrlCriteria { get; set; }
        public List<QRCodeUrlDetailViewModel> QrCodeUrlResults { get; set; }

        // lookups
        public List<Division> Divisions { get; set; }
    }
}

Src/ListingRepository.Web/ListingRepository.Web/Controllers/ReportListController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Postmedia.ListingRepository.DTO;
using Postmedia.ListingRepository.DTO.Reports;
using Postmedia.ListingRepository.DTO.Reports.Working;
using Postmedia.ListingRepository.Web.ViewModels.Reports;
using Postmedia.ListingRepository.Web.ViewModels.Reports.Working;
using Postmedia.ListingRepository.Core.Communication;


namespace Postmedia.ListingRepository.Web.Controllers
{
    public class ReportListController : Controller
    {
        //
        // GET: /ReportList/
        public ActionResult Index()
        {
            return View();
        }

        // GET: /ReportList/WorkingSAMSSearch/
        public ActionResult WorkingSAMSSearch(SAMSSearchViewModel svm)
        {
            // populate the divisions lookup
            var divisions = RESTClient.Instance.Call<List<Division>>(RESTMethod.GetDivisions);
            svm.Divisions = divisions;

            // check if the view model is null (first time hitting page)
            if (svm.SamsCriteria == null)
            {
                // if true then create a new viewmodel
                svm.SamsCriteria = new SAMSCriteriaViewModel(null);

                // set up some default summaries values
                var defaultDate = DateTime.Today;
                svm.SamsCriteria.Date = defaultDate;
            }

            if (ModelState.IsValid)
            {
                var results = RESTClient.Instance.Call<SamsCriteria, List<SamsResult>>(svm.SamsCriteria.getDTOForReport(), RESTMethod.GetWorkingSamsReport);
                svm.SamsResults = new List<SamsDetailViewModel>();
                foreach (var workdetail in results)
                {
                    svm.SamsResults.Add(new SamsDetailViewModel(workdetail));
                }
            }
            return View(svm);
        }


        // GET: /ReportList/WorkingSamsNoFeedbackSearch/
        public ActionResult WorkingSamsNoFeedbackSearch(SamsNoFeedbackSearchViewModel svm)
        {
            // populate the divisions lookup
            var divisions = RESTClient.Instance.Call<List<Division>>(RESTMethod.GetDivisions);
            svm.Divisions = divisions;

            // check if the view model is null (first time hitting page)
            if (svm.SamsNoFeedbackCriteria == null)
            {
                // if true then create a new viewmodel
                svm.SamsNoFeedbackCriteria = new SamsNoFeedbackCriteriaViewModel(null);

                // set up some default summaries values
                var defaultDate = DateTime.Today;
                svm.SamsNoFeedbackCriteria.Date = defaultDate;
            }

            if (ModelState.IsValid)
            {
                var results = RESTClient.Instance.Call<SamsNoFeedbackCriteria, List<SamsNoFeedbackResult>>(svm.SamsNoFeedbackCriteria.getDTOForReport(), RESTMethod.GetWorkingSamsNoFeedbackReport);
                svm.SamsNoFeedbackResults = new List<SamsNoFeedbackDetailViewModel>();
                foreach (var workdetail in results)
                {
                    svm.SamsNoFeedbackResults.Add(new SamsNoFeedbackDetailViewModel(workdetail));
                }
            }
            return View(svm);
        }
        
        
        
        // GET: /ReportList/WorkingDigitalDisplaySearch/
        public ActionResult QRCodeUrlSearch(QRCodeUrlSearchViewModel ddvm)
        {
            // populate the divisions lookup
            var divisions = RESTClient.Instance.Call<List<Division>>(RESTMethod.GetDivisions);
            ddvm.Divisions = divisions;

            // check if the view model is null (first time hitting page)
            if (ddvm.QrCodeUrlCriteria == null)
            {
                // if true then create a new viewmodel
                ddvm.QrCodeUrlCriteria = new QRCodeUrlCriteriaViewModel(null);

                // set up some default summaries values
                var defaultDate = DateTime.Today;
                ddvm.QrCodeUrlCriteria.Date = defaultDate;
            }

            if (ModelState.IsValid)
            {
                var results = RESTClient.Instance.Call<QRCodeUrlCriteria, List<QRCodeUrlResult>>(ddvm.QrCodeUrlCriteria.getDTOForReport(), RESTMethod.GetQRCodeUrlReport);
                ddvm.QrCodeUrlResults = new List<QRCodeUrlDetailViewModel>();
                foreach (var workdetail in results)
                {
                    ddvm.QrCodeUrlResults.Add(new QRCodeUrlDetailViewModel(workdetail));
                }
            }
            return View(ddvm);
        }

        // GET: /ReportList/WorkingUpsellSearch/
        public ActionResult WorkingUpsellSearch(UpsellSearchViewModel uvm)
        {
            // populate the divisions lookup
            var divisions = RESTClient.Instance.Call<List<Division>>(RESTMethod.GetDivisions);
            uvm.Divisions = divisions;

            // check if the view model is null (first time hitting page)
            if (uvm.UpsellCriteria == null)
            {
                // if true then create a new viewmodel
                uvm.UpsellCriteria = new UpsellCriteriaViewModel(null);

                // set up some default summaries values
                uvm.UpsellCriteria.StartDate = DateTime.Today.AddDays(-7);
                uvm.UpsellCriteria.EndDate = DateTime.Today;
            }

            if (ModelState.IsValid)
            {
                var results = RESTClient.Instance.Call<UpsellCriteria, List<UpsellResult>>(uvm.UpsellCriteria.getDTOForReport(), RESTMethod.GetWorkingUpsellReport);
                uvm.UpsellResults = new List<UpsellDetailViewModel>();
                foreach (var upselldetail in results)
                {
                    uvm.UpsellResults.Add(new UpsellDetailViewModel(upselldetail));
                }
            }
            return View(uvm);
        }

        public ActionResult DetailedUpsellSearch(DetailedUpsellSearchViewModel dvm)
        {
            var divisions = RESTClient.Instance.Call<List<Division>>(RESTMethod.GetDivisions);
            var upsellValues = RESTClient.Instance.Call<List<UpsellValueLookup>>(RESTMethod.GetUpsellValues);
            var publications = RESTClient.Instance.Call<List<Publication>>(RESTMethod.GetPublications);
            var status = RESTClient.Instance.Call<List<ListingStatusLookup>>(RESTMethod.GetListingStatuses);
            var sources = RESTClient.Instance.Call<List<SourceSystemLookup>>(RESTMethod.GetSourceSystems);
            
            dvm.Divisions = divisions;
            dvm.Sources = sources;
            dvm.UpsellValues = upsellValues;
            dvm.Publications = publications;
            dvm.Status = status;

            if (dvm.DetailedUpsellCriteria == null)
            {
                dvm.DetailedUpsellCriteria = new DetailedUpsellCriteriaViewModel(null);
                var firstOfTheMonth = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1);
                dvm.DetailedUpsellCriteria.PublicationCode = "40";
                dvm.DetailedUpsellCriteria.UpsellCode = "FEAT";
                dvm.DetailedUpsellCriteria.StartDate1 = firstOfTheMonth;
                dvm.DetailedUpsellCriteria.StartDate2 = firstOfTheMonth.AddMonths(1).AddDays(-1);
            }

            if (ModelState.IsValid)
            {
                var results =
                    RESTClient.Instance.Call<DetailedUpsellCriteria, List<DetailedUpsellResult>>(
                        dvm.DetailedUpsellCriteria.getDTOForReport(), RESTMethod.GetDetailedUpsellReport);
                
                dvm.DetailedUpsellResults = new List<DetailedUpsellDetailViewModel>();

                foreach (var result in results)
                {
                    dvm.DetailedUpsellResults.Add(new DetailedUpsellDetailViewModel(result));
                }

                //if (dvm.DetailedUpsellCriteria.PublishDayFilter != null) dvm.DetailedUpsellResults = dvm.DetailedUpsellResults.FindAll(x => x.PublishingDays == dvm.DetailedUpsellCriteria.PublishDayFilter);
            }

            return View(dvm);
        }        
    }
}

Src/ListingRepository.Web/ListingRepository.Web/Views/ReportList/DetailedUpsellSearch.cshtml
@model Postmedia.ListingRepository.Web.ViewModels.Reports.DetailedUpsellSearchViewModel

@{
    ViewBag.Title = "Detailed Upsell Search";
}

<div class="criteria">
    <h2>Detailed Upsell Search Criteria</h2>  

    @using (Html.BeginForm("DetailedUpsellSearch", "ReportList", FormMethod.Get, new { enctype = "multipart/form-Data" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <!-- Division criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.DetailedUpsellCriteria.DivisionCode)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.DetailedUpsellCriteria.DivisionCode, new SelectList(Model.Divisions, "Code", "Name", Model.DetailedUpsellCriteria.DivisionCode), "--Select Division--")
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.DivisionCode)
            </span>
            
            <br />

            <!-- Listing Source criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.DetailedUpsellCriteria.ListingSource)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.DetailedUpsellCriteria.ListingSource, new SelectList(Model.Sources, "Value", "Value", Model.DetailedUpsellCriteria.ListingSource), "--Select Source--")
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.ListingSource)
            </span>
            
            <br />
            
            <!-- Publication criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.DetailedUpsellCriteria.PublicationCode)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.DetailedUpsellCriteria.PublicationCode, new SelectList(Model.Publications, "Code", "Name", Model.DetailedUpsellCriteria.PublicationCode), "--Select Publication--")
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.PublicationCode)
            </span>
            
            <br />

            <!-- Upsell criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.DetailedUpsellCriteria.UpsellCode)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.DetailedUpsellCriteria.UpsellCode, new SelectList(Model.UpsellValues, "Code", "Value", Model.DetailedUpsellCriteria.UpsellCode), "--Select Upsell--")
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.UpsellCode)
            </span>
            
            <br />
            
            <!-- Status criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.DetailedUpsellCriteria.ListingPubStatus)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.DetailedUpsellCriteria.ListingPubStatus, new SelectList(Model.Status, "Value", "Value", Model.DetailedUpsellCriteria.ListingPubStatus), "--Select Status--")
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.ListingPubStatus)
            </span>
            
            <br />
            
            
            <span class="editor-label">
                <b>Start Date Between:</b>
            </span>
            <span class="editor-field">
                @Html.EditorFor(model => model.DetailedUpsellCriteria.StartDate1, new { style = "width: 120px" })
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.StartDate1)
            </span>
            <span class="editor-label">
                <b> AND </b>
            </span>
            <span class="editor-field">
                @Html.EditorFor(model => model.DetailedUpsellCriteria.StartDate2, new { style = "width: 120px" })
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.StartDate2)
            </span>
    
            <br />
            <span class="editor-label">
                <b>Expire Date Between:</b>
            </span>
            <span class="editor-field">
                @Html.EditorFor(model => model.DetailedUpsellCriteria.ExpireDate1, new { style = "width: 120px" })
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.ExpireDate1)
            </span>

            <span class="editor-label">
                <b> AND </b>
            </span>
            <span class="editor-field">
                @Html.EditorFor(model => model.DetailedUpsellCriteria.ExpireDate2, new { style = "width: 120px" })
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.ExpireDate2)
            </span>
            
            <br />
            <span class="editor-label">
                @Html.LabelFor(model => model.DetailedUpsellCriteria.PublishDayFilter)
            </span>
            <span class="editor-field">
                <!--Html.DropDownListFor(model => Model.DetailedUpsellCriteria.PublishDayFilter, new SelectList(Model.PublishDayFilters, "Value", "Name", Model.DetailedUpsellCriteria.PublishDayFilter))-->
                @Html.EditorFor(model => model.DetailedUpsellCriteria.PublishDayFilter)
                @Html.ValidationMessageFor(model => model.DetailedUpsellCriteria.PublishDayFilter)
            </span>
            
            <!-- Email Criteria -->
            <br />
            <span>
                @Html.LabelFor(model => model.DetailedUpsellCriteria.EmailResults)
            </span>
            <span>
                @Html.CheckBoxFor(model => model.DetailedUpsellCriteria.EmailResults)
            </span>

            <span>
                @Html.LabelFor(model => model.DetailedUpsellCriteria.EmailAddress)
            </span>
            <span>
                @Html.EditorFor(model => model.DetailedUpsellCriteria.EmailAddress)
            </span>
            <p>
                <input type="submit" value="Search"  />
            </p>
            
            <div>
                Record Count: @Model.DetailedUpsellResults.Count
            </div>
        </fieldset>
    }
</div>


<div class="results">
@{
    int pageSize;
    //var wg = new WebGrid(rowsPerPage: int.TryParse(ViewData["GetPageSize"].ToString(), out pageSize) ? pageSize : 25) as WebGrid;
    var wg = new WebGrid(rowsPerPage: int.TryParse("25", out pageSize) ? pageSize : 25) as WebGrid;
    if (Model.DetailedUpsellResults != null)
    {
        wg.Bind(Model.DetailedUpsellResults, rowCount: Model.DetailedUpsellResults.Count, autoSortAndPage: true);
        @wg.GetHtml(
        //mode:WebGridPagerModes.Numeric|WebGridPagerModes.NextPrevious,
            mode: WebGridPagerModes.All,
            nextText: "Next",
            previousText: "Previous",
            firstText: "First",
            lastText: "Last (" + wg.PageCount + ")",
            htmlAttributes: new { id = "grid" },
            columns: wg.Columns(
                wg.Column("Source", "Source"),
                wg.Column("DivisionName", "Division Name"),
                wg.Column("ListingNumber", "Listing Number"),
                wg.Column("PublicationName", "Publication"),
                wg.Column("Title", "Title"),
                wg.Column("UpsellName", "Upsell"),
                wg.Column("Status", "Status"),
                wg.Column("StartDate", "StartDate"),
                wg.Column("ExpireDate", "ExpireDate"),
                wg.Column("PublishingDays", "Publishing Days"),
                wg.Column(format: (item) => Html.ActionLink("View Details", "ViewDetail", "Home", new { id = item.listingid }, null))
                )
        );
    }
    else
    {
        <p>-- No Records Found --</p>
    }         
}
</div>

Src/ListingRepository.Web/ListingRepository.Web/Views/ReportList/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Report List</h2>

<div>
    <ul>
        <li>@Html.ActionLink("Upsell Report", "WorkingUpsellSearch")</li>
        <li>@Html.ActionLink("SAMS Working Ads", "WorkingSAMSSearch")</li>
        <li>@Html.ActionLink("SAMS Employment Missed Ads", "WorkingSamsNoFeedbackSearch")</li>
        <li>@Html.ActionLink("QR Code Url Report", "QRCodeUrlSearch")</li>
        <li>@Html.ActionLink("Detailed Upsell Report", "DetailedUpsellSearch")</li>
    </ul>
</div>

Src/ListingRepository.Web/ListingRepository.Web/Views/ReportList/QRCodeUrlSearch.cshtml
@model Postmedia.ListingRepository.Web.ViewModels.Reports.Working.QRCodeUrlSearchViewModel
@{
    ViewBag.Title = "QR Code Url Report";
}

<div class="criteria">
    <h2>QR Code Url Search Criteria</h2>  

    @using (Html.BeginForm("QRCodeUrlSearch", "ReportList", FormMethod.Post, new { enctype = "multipart/form-Data" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <!-- Division criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.QrCodeUrlCriteria.Division)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.QrCodeUrlCriteria.Division, new SelectList(Model.Divisions, "Code", "Name", Model.QrCodeUrlCriteria.Division), "--Select Division--")
                @Html.ValidationMessageFor(model => model.QrCodeUrlCriteria.Division)
            </span>

            <!-- Date.  Service will retrieve any records where date >= StartDate and <= ExpireDate -->
            <span class="editor-label">
                @Html.LabelFor(model => model.QrCodeUrlCriteria.Date)
            </span>
            <span class="editor-field">
                @Html.EditorFor(model => model.QrCodeUrlCriteria.Date)
                @Html.ValidationMessageFor(model => model.QrCodeUrlCriteria.Date)
            </span>
    
            <!-- Email Criteria -->
            <br />
            <span>
                @Html.LabelFor(model => model.QrCodeUrlCriteria.EmailResults)
            </span>
            <span>
                @Html.CheckBoxFor(model => model.QrCodeUrlCriteria.EmailResults)
            </span>

            <span>
                @Html.LabelFor(model => model.QrCodeUrlCriteria.EmailAddress)
            </span>
            <span>
                @Html.EditorFor(model => model.QrCodeUrlCriteria.EmailAddress)
            </span>
            <p>
                <input type="submit" value="Search"  />
            </p>
        </fieldset>
    }
</div>

<div class="results">
    <h2>Search Results...</h2>

    <table>
        <tr>
            <th>
                Division
            </th>
            <th>
                Publication
            </th>
            <th>
                Ad Number
            </th>
            <th>
                Account
            </th>
            <th>
                Title
            </th>
            <th>
                Category
            </th>
            <th>
                Start Date
            </th>
            <th>
                Expiry Date
            </th>
            <th>
                Ad Length
            </th>
            <th>
                Display URL
            </th>
        </tr>
        @if (Model.QrCodeUrlResults != null)
        {
            foreach (var item in Model.QrCodeUrlResults)
            {
                <tr id="row-@item">
                    <td>
                        @item.DivisionName
                    </td>
                    <td>
                        @item.PublicationName
                    </td>
                    <td>
                        @item.ListingNumber
                    </td>
                    <td>
                        @item.Advertiser
                    </td>
                    <td>
                        @item.Title
                    </td>
                    <td>
                        @item.Category
                    </td>
                    <td>
                        @item.StartDate
                    </td>
                    <td>
                        @item.ExpireDate
                    </td>
                    <td class="@item.AdLengthStyle">
                        @item.AdLength
                    </td>
                    <td class="@item.DisplayURLStyle">
                        @item.DisplayURL
                    </td>
                </tr>
            }
        }
        @if (Model.QrCodeUrlResults == null || Model.QrCodeUrlResults.Count == 0)
        { 
            <tr>
            <td colspan="10">-- No Records Found --</td>
            </tr>            
        }
    </table>
</div>

Src/ListingRepository.Web/ListingRepository.Web/Views/ReportList/SAMSWorkingSearch.cshtml
@model Postmedia.ListingRepository.Web.ViewModels.Reports.WorkingSAMSSearchViewModel
@{
    ViewBag.Title = "SAMS Working Search";
}

<h2>SAMS Working Search</h2>

<div class="criteria">
    <h2>Search Criteria</h2>  

    @using (Html.BeginForm("SAMSWorkingSearch", "ReportList", FormMethod.Post, new { enctype = "multipart/form-Data" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <!-- Division criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.WorkingSAMSCriteria.Division)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.WorkingSAMSCriteria.Division, new SelectList(Model.Divisions, "Code", "Name", Model.WorkingSAMSCriteria.Division), "--Select Division--")
                @Html.ValidationMessageFor(model => model.WorkingSAMSCriteria.Division)
            </span>

            <!-- Date.  Service will retrieve any records where date >= StartDate and <= ExpireDate -->
            <span class="editor-label">
                @Html.LabelFor(model => model.WorkingSAMSCriteria.Date)
            </span>
            <span class="editor-field">
                @Html.EditorFor(model => model.WorkingSAMSCriteria.Date)
                @Html.ValidationMessageFor(model => model.WorkingSAMSCriteria.Date)
            </span>
    
            <p>
                <input type="submit" value="Search"  />
            </p>
        </fieldset>
    }
</div>



<div class="results">
    <h2>Search Results...</h2>

    <table>
        <tr>
            <th>
                Division
            </th>
            <th>
                Ad Number                
            </th>
            <th>
                Account
            </th>
            <th>
                Title
            </th>
            <th>
                Category
            </th>
            <th>
                Start Date
            </th>
            <th>
                Expiry Date
            </th>
            <th>
                Ad Length
            </th>
        </tr>
        @if (Model.WorkingSAMSResults != null)
        {
            foreach (var item in Model.WorkingSAMSResults)
            {
                <tr id="row-@item">
                    <td>
                        @item.Division
                    </td>
                    <td>
                        @item.ListingNumber
                    </td>
                    <td>
                        @item.Account
                    </td>
                    <td>
                        @item.Title
                    </td>
                    <td>
                        @item.Category
                    </td>
                    <td>
                        @item.StartDate
                    </td>
                    <td>
                        @item.ExpireDate
                    </td>
                    <td>
                        @item.AdLength
                    </td>
                </tr>
            }
        }
    </table>
</div>

Src/ListingRepository.Web/ListingRepository.Web/Views/ReportList/WorkingDigitalDisplaySearch.cshtml
@model Postmedia.ListingRepository.Web.ViewModels.Reports.Working.DigitalDisplaySearchViewModel
@{
    ViewBag.Title = "Working Digital Display Report";
}

<div class="criteria">
    <h2>Working Digital Display Search Criteria</h2>  

    @using (Html.BeginForm("WorkingDigitalDisplaySearch", "ReportList", FormMethod.Post, new { enctype = "multipart/form-Data" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <!-- Division criteria -->
            <span class="editor-label">
                @Html.LabelFor(model => model.DigitalDisplayCriteria.Division)
            </span>
            <span class="editor-field">
                @Html.DropDownListFor(model => model.DigitalDisplayCriteria.Division, new SelectList(Model.Divisions, "Code", "Name", Model.DigitalDisplayCriteria.Division), "--Select Division--")
                @Html.ValidationMessageFor(model => model.DigitalDisplayCriteria.Division)
            </span>

            <!-- Date.  Service will retrieve any records where date >= StartDate and <= ExpireDate -->
            <span class="editor-label">
                @Html.LabelFor(model => model.DigitalDisplayCriteria.Date)
            </span>
            <span class="editor-field">
                @Html.EditorFor(model => model.DigitalDisplayCriteria.Date)
                @Html.ValidationMessageFor(model => model.DigitalDisplayCriteria.Date)
            </span>
    
            <!-- Email Criteria -->
            <br />
            <span>
                @Html.LabelFor(model => model.DigitalDisplayCriteria.EmailResults)
            </span>
            <span>
                @Html.CheckBoxFor(model => model.DigitalDisplayCriteria.EmailResults)
            </span>

            <span>
                @Html.LabelFor(model => model.DigitalDisplayCriteria.EmailAddress)
            </span>
            <span>
                @Html.EditorFor(model => model.DigitalDisplayCriteria.EmailAddress)
            </span>
            <p>
                <input type="submit" value="Search"  />
            </p>
        </fieldset>
    }
</div>

<div class="results">
    <h2>Search Results...</h2>

    <table>
        <tr>
            <th>
                Division
            </th>
            <th>
                Publication
            </th>
            <th>
                Ad Number
            </th>
            <th>
                Account
            </th>
            <th>
                Title
            </th>
            <th>
                Category
            </th>
            <th>
                Start Date
            </th>
            <th>
                Expiry Date
            </th>
            <th>
                Ad Length
            </th>
            <th>
                Display URL
            </th>
        </tr>
        @if (Model.DigitalDisplayResults != null)
        {
            foreach (var item in Model.DigitalDisplayResults)
            {
                <tr id="row-@item">
                    <td>
                        @item.DivisionName
                    </td>
                    <td>
                        @item.PublicationName
                    </td>
                    <td>
                        @item.ListingNumber
                    </td>
                    <td>
                        @item.Advertiser
                    </td>
                    <td>
                        @item.Title
                    </td>
                    <td>
                        @item.Category
                    </td>
                    <td>
                        @item.StartDate
                    </td>
                    <td>
                        @item.ExpireDate
                    </td>
                    <td class="@item.AdLengthStyle">
                        @item.AdLength
                    </td>
                    <td class="@item.DisplayURLStyle">
                        @item.DisplayURL
                    </td>
                </tr>
            }
        }
        @if (Model.DigitalDisplayResults == null || Model.DigitalDisplayResults.Count == 0)
        { 
            <tr>
            <td colspan="10">-- No Records Found --</td>
            </tr>            
        }
    </table>
</div>